#!/bin/bash

module load kvl-remote
module load paraview/4.3.1-openmpi-x86_64


HOSTFILE=/home/srinivm/develop/github/kvl/ParaView/Scripts/launch/gpgpu/hosts
NUM_PROCS=64

/usr/lib64/openmpi/bin/mpirun -x LD_LIBRARY_PATH -x PATH -x PYTHONPATH  -hostfile $HOSTFILE -np $NUM_PROCS -npernode 8 /home/srinivm/develop/github/kvl/ParaViewCatalystExampleCode/build/KVLInSituExample-001/KVLInSituExample001 /home/srinivm/develop/github/kvl/ParaViewCatalystExampleCode/KVLInSituExample-001/SampleScripts/streamlineslicescript.py
