#!/bin/bash

module load paraview/4.3.1-openmpi-dev


HOSTFILE=/home/srinivm/develop/github/kvl/ParaViewCatalystExampleCode/KVLInSituExample-001/z5.hostnames
NUM_PROCS=64

/usr/lib64/openmpi/bin/mpirun -x DISPLAY=:0.0 -x LD_LIBRARY_PATH -x PATH -x PYTHONPATH  -hostfile $HOSTFILE -np $NUM_PROCS -npernode 8 /home/srinivm/develop/github/kvl/ParaViewCatalystExampleCode/build/KVLInSituExample-001/KVLInSituExample001 /home/srinivm/develop/github/kvl/ParaViewCatalystExampleCode/KVLInSituExample-001/SampleScripts/streamlinescript.py
