#!/bin/bash

module load kvl-remote
module load paraview/4.3.1

mpirun -genvlist LD_LIBRARY_PATH,PATH,PYTHONPATH  -hosts gpgpu-01,gpgpu-02,gpgpu-03,gpgpu-04 -np 5 /home/srinivm/develop/github/kvl/ParaViewCatalystExampleCode/build/KVLInSituExample-001/KVLInSituExample001
